from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.colors import HexColor
import io

def export_to_pdf(data: dict) -> bytes:
    """
    Exports the full ClarifyQA analysis as a PDF report.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=inch, leftMargin=inch,
                            topMargin=inch, bottomMargin=inch)

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle('Title', fontSize=20, textColor=HexColor('#00bcd4'),
                                  spaceAfter=12, fontName='Helvetica-Bold')
    heading_style = ParagraphStyle('Heading', fontSize=13, textColor=HexColor('#00bcd4'),
                                    spaceAfter=8, spaceBefore=16, fontName='Helvetica-Bold')
    body_style = ParagraphStyle('Body', fontSize=10, spaceAfter=6,
                                 leading=16, fontName='Helvetica')
    req_style = ParagraphStyle('Req', fontSize=11, textColor=HexColor('#888888'),
                                spaceAfter=12, fontName='Helvetica-Oblique')

    story = []

    story.append(Paragraph("ClarifyQA Analysis Report", title_style))
    story.append(Paragraph(f"Requirement: {data.get('requirement', '')}", req_style))
    story.append(Spacer(1, 12))

    sections = [
        ("📊 Requirement Readiness Score", "score"),
        ("🔎 QA Review — User Story Readiness", "qa_review"),
        ("⚠️ Ambiguity Detector", "ambiguity"),
        ("✏️ Before vs After Improvement", "improved"),
        ("✅ Acceptance Criteria", "acceptance"),
        ("🧪 Test Coverage Checklist", "coverage"),
        ("🐛 Bug Severity & Priority", "severity"),
        ("📋 Jira Bug Report", "jira"),
        ("🔄 Regression Impact Analysis", "regression"),
        ("📋 Requirement Analysis", "analysis"),
        ("🧠 Strategy & Risk Plan", "strategy"),
        ("⚙️ Test Scenarios & Bug Report", "output"),
    ]

    for title, key in sections:
        story.append(Paragraph(title, heading_style))
        content = data.get(key, "")
        for line in content.split('\n'):
            line = line.strip()
            if line:
                safe_line = line.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                story.append(Paragraph(safe_line, body_style))
        story.append(Spacer(1, 8))

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by ClarifyQA — AI Reasoning Agent for QA Engineers",
                            ParagraphStyle('Footer', fontSize=8, textColor=HexColor('#555555'))))

    doc.build(story)
    return buffer.getvalue()